FROM python:3.13-slim-bookworm

RUN pip install --no-cache-dir huggingface_hub==0.34.4

COPY download-model.sh /usr/local/bin/download-model
RUN chmod 0755 /usr/local/bin/download-model

ENTRYPOINT ["/usr/local/bin/download-model"]
